name: Publish Docker
on:
  push:
    branches:
      - master
      - "v[0-9]+"
    tags:
      - "v[0-9.]+"
  schedule:
    - cron: "23 9 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/docwhat/jq-docker/jq
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.io/docwhat/jq
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
