name: Build & Publish
on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/push.yaml"
    branches:
      - main
    tags:
      - "v[1-9]*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/docwhat/jq-docker/jq
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_semver: true
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.io/docwhat/jq
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
      - name: Publish to Quay
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: quay.io/docwhat/jq
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          tag_semver: true
      - name: pushover-actions
        uses: clivern/pushover-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
